name: bt tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        build_type: [Debug, Release]
        os: [macos-latest, ubuntu-latest]
        cpp_compiler: [g++-13, clang++]
        include:
          - os: ubuntu-latest
            c_compiler: gcc-13
            cpp_compiler: g++-13
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: macos-latest
            cpp_compiler: g++-13
          - os: ubuntu-latest
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Install gcc-13
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update -y && sudo apt-get install gcc-13 g++-13 -y
        fi;
        exit 0
      shell: bash

    - name: Install Conan
      run: pip install conan

    - name: Configure Conan
      run: conan profile detect

    - name: Install Requirements
      working-directory: ./tests
      run: >
        conan install .
        --output-folder=./build
        --build=missing -s compiler.cppstd=20
        -s build_type=${{ matrix.build_type }}

    - name: Configure CMake
      working-directory: ./tests
      run: >
        cmake -B build -S .
        -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}

    - name: Build Tests
      working-directory: ./tests/build
      run: make bt_tests

    - name: Run Tests
      working-directory: ./tests/build
      run: ctest --test-dir . --output-on-failure

    - name: Build benchmark
      working-directory: ./tests/build
      run: make bt_benchmark

    - name: Run Benchmark
      working-directory: ./tests/build
      run: ./bt_benchmark
